"use strict";

const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const PAGE_SIZE = 20;
const state = { notices: [], markets: [], providers: [], trends: [], locations: [], jobs: [], jobHistory: [], jobMeta: {}, newJobIds: new Set(), metadata: {}, page: 1, saved: new Set(JSON.parse(localStorage.getItem("lq-education-saved") || "[]")) };
const number = new Intl.NumberFormat("en-US");
const date = new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" });
const stateNames = { AL:"Alabama",AK:"Alaska",AZ:"Arizona",AR:"Arkansas",CA:"California",CO:"Colorado",CT:"Connecticut",DE:"Delaware",DC:"District of Columbia",FL:"Florida",GA:"Georgia",HI:"Hawaii",ID:"Idaho",IL:"Illinois",IN:"Indiana",IA:"Iowa",KS:"Kansas",KY:"Kentucky",LA:"Louisiana",ME:"Maine",MD:"Maryland",MA:"Massachusetts",MI:"Michigan",MN:"Minnesota",MS:"Mississippi",MO:"Missouri",MT:"Montana",NE:"Nebraska",NV:"Nevada",NH:"New Hampshire",NJ:"New Jersey",NM:"New Mexico",NY:"New York",NC:"North Carolina",ND:"North Dakota",OH:"Ohio",OK:"Oklahoma",OR:"Oregon",PA:"Pennsylvania",RI:"Rhode Island",SC:"South Carolina",SD:"South Dakota",TN:"Tennessee",TX:"Texas",UT:"Utah",VT:"Vermont",VA:"Virginia",WA:"Washington",WV:"West Virginia",WI:"Wisconsin",WY:"Wyoming",PR:"Puerto Rico" };
const validationSources = [
  { name:"NAEYC Accredited Early Learning Programs", organization:"National Association for the Education of Young Children", type:"program", priority:"BrightPath primary", url:"https://my.naeyc.org/s/searchdirectory", description:"Verify the accreditation status of a specific childcare or early-learning location." },
  { name:"State Licensing and Inspection Reports", organization:"ChildCare.gov", type:"licensing", priority:"Required", url:"https://childcare.gov/consumer-education/regulated-child-care/monitoring-and-inspections", description:"Reach state and territory licensing resources, monitoring records, violations, and inspection reports." },
  { name:"NECPA Accredited Program Lookup", organization:"National Early Childhood Program Accreditation", type:"program", priority:"Alternative national", url:"https://necpa.net/programs", description:"Search programs accredited through NECPA's early-childhood quality system." },
  { name:"NAEYC Accredited Higher Education Programs", organization:"NAEYC Commission on Higher Education Accreditation", type:"workforce", priority:"Talent pipeline", url:"https://www.naeyc.org/accreditation/higher-ed/accredited-programs", description:"Validate colleges and degree programs preparing early-childhood educators." },
  { name:"NAFCC Accreditation", organization:"National Association for Family Child Care", type:"program", priority:"Family childcare", url:"https://nafcc.org/accreditation/", description:"Review accreditation resources and accredited educators in family childcare settings." },
  { name:"Head Start Center Locator", organization:"Office of Head Start", type:"licensing", priority:"Federal program", url:"https://headstart.gov/center-locator", description:"Validate Head Start and Early Head Start service locations by geography or grant number." },
  { name:"Cognia Institution Registry", organization:"Cognia", type:"specialty", priority:"School accreditation", url:"https://home.cognia.org/registry", description:"Search Cognia's institution registry, including eligible early-learning and PreK–12 organizations." },
  { name:"American Montessori Society Directory", organization:"American Montessori Society", type:"specialty", priority:"Montessori", url:"https://amshq.org/schools/", description:"Validate Montessori school affiliation and pathway status by location or keyword." }
];

function escapeHtml(value = "") { return String(value).replace(/[&<>"']/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#039;" }[char])); }
function formatDate(value) { if (!value) return "Not reported"; const parsed = new Date(`${value}T12:00:00`); return Number.isNaN(parsed.getTime()) ? value : date.format(parsed); }
function friendlyState(code) { return stateNames[code] || code; }
function routeTo(route) { $$(".nav-link").forEach(item => item.classList.toggle("active", item.dataset.route === route)); $$(".view").forEach(view => view.classList.toggle("active", view.dataset.view === route)); history.replaceState(null, "", `#${route}`); if (route === "saved") renderSaved(); scrollTo({ top: 0, behavior: "smooth" }); }
function populateSelect(element, values) { values.filter(Boolean).sort().forEach(value => { const option = document.createElement("option"); option.value = value; option.textContent = `${friendlyState(value)} (${value})`; element.append(option); }); }

function filters() { return { query: $("#notice-search").value.trim().toLowerCase(), selectedState: $("#notice-state").value, windowDays: $("#notice-window").value, minScore: Number($("#notice-score").value) }; }
function filteredNotices() {
  const f = filters(); const now = Date.now();
  return state.notices.filter(item => {
    if (f.selectedState && item.state !== f.selectedState) return false;
    if (Number(item.relevance_score || 0) < f.minScore) return false;
    if (f.query && ![item.employer_name,item.organization_name,item.site_name,item.city,item.county,item.state,item.provider_type].join(" ").toLowerCase().includes(f.query)) return false;
    if (f.windowDays !== "all") { const value = item.effective_date || item.notice_date; if (!value) return false; if (Math.abs(new Date(`${value}T12:00:00`).getTime() - now) > Number(f.windowDays) * 86400000) return false; }
    return true;
  });
}
function scoreClass(score) { return score >= 90 ? "high" : score >= 80 ? "medium" : ""; }
function noticeCard(item) {
  const saved = state.saved.has(item.id); const location = [item.city,item.state].filter(Boolean).join(", ") || "Location unavailable";
  return `<article class="notice-card" data-notice-id="${escapeHtml(item.id)}" tabindex="0"><div class="score-badge ${scoreClass(item.relevance_score)}" title="Directional relevance score">${item.relevance_score}</div><div class="notice-main"><h3>${escapeHtml(item.employer_name || "Unknown provider")}</h3><p>${escapeHtml(location)} · <span class="tag">${escapeHtml(item.provider_type)}</span></p></div><div class="notice-meta"><strong>${item.employees_affected ? `${number.format(item.employees_affected)} workers` : "Count unavailable"}</strong><p>Effective ${formatDate(item.effective_date)}</p></div><div class="notice-actions"><button class="icon-button ${saved ? "saved" : ""}" data-save-id="${escapeHtml(item.id)}" aria-label="${saved ? "Remove from saved" : "Save signal"}">${saved ? "★" : "☆"}</button><button class="icon-button" data-open-id="${escapeHtml(item.id)}" aria-label="View details">→</button></div></article>`;
}
function renderNotices() { const items = filteredNotices(); const pages = Math.max(1, Math.ceil(items.length / PAGE_SIZE)); state.page = Math.min(state.page, pages); const start = (state.page - 1) * PAGE_SIZE; $("#notice-list").innerHTML = items.length ? items.slice(start,start + PAGE_SIZE).map(noticeCard).join("") : '<div class="empty-card">No signals match these filters.</div>'; $("#result-count").textContent = `${number.format(items.length)} result${items.length === 1 ? "" : "s"}`; $("#page-label").textContent = `Page ${state.page} of ${pages}`; $("#prev-page").disabled = state.page <= 1; $("#next-page").disabled = state.page >= pages; }
function renderSaved() { const items = state.notices.filter(item => state.saved.has(item.id)); $("#saved-list").innerHTML = items.length ? items.map(noticeCard).join("") : '<div class="empty-card">No saved signals yet. Select the star on a notice to start a watchlist.</div>'; }
function saveNotice(id) { state.saved.has(id) ? state.saved.delete(id) : state.saved.add(id); localStorage.setItem("lq-education-saved", JSON.stringify([...state.saved])); $("#saved-count").textContent = state.saved.size; renderNotices(); renderSaved(); }
function renderMarkets() { const query = $("#market-search").value.trim().toLowerCase(); const items = state.markets.filter(item => `${item.state} ${friendlyState(item.state)}`.toLowerCase().includes(query)); $("#market-count").textContent = `${items.length} market${items.length === 1 ? "" : "s"}`; $("#market-list").innerHTML = items.length ? items.map(item => `<article class="program-card"><span class="level">Activity ${item.activity_index}</span><span class="accreditor">${escapeHtml(item.state)}</span><h3>${escapeHtml(friendlyState(item.state))}</h3><p>${number.format(item.events)} workforce signal${item.events === 1 ? "" : "s"}</p><p>${number.format(item.workers_affected)} reported workers affected</p><p>${number.format(item.providers)} matched provider${item.providers === 1 ? "" : "s"}</p><a href="#radar" data-market-state="${escapeHtml(item.state)}">View state signals →</a></article>`).join("") : '<div class="empty-card">No markets match this search.</div>'; }
function renderComparison() { const a = state.markets.find(item => item.state === $("#compare-a").value); const b = state.markets.find(item => item.state === $("#compare-b").value); if (!a || !b) return; const metrics = [["Activity index","activity_index"],["Signals","events"],["Workers affected","workers_affected"],["Providers","providers"]]; $("#market-comparison").innerHTML = `<div class="compare-head"><strong>${escapeHtml(friendlyState(a.state))}</strong><span>vs</span><strong>${escapeHtml(friendlyState(b.state))}</strong></div>${metrics.map(([label,key]) => `<div class="compare-row"><strong>${number.format(a[key])}</strong><span>${label}</span><strong>${number.format(b[key])}</strong></div>`).join("")}<div class="comparison-callout">${a.activity_index === b.activity_index ? "Both markets have the same activity index." : `${escapeHtml(friendlyState(a.activity_index > b.activity_index ? a.state : b.state))} currently shows the stronger directional activity signal.`}</div>`; }
function renderEmployers() { const query = $("#employer-search").value.trim().toLowerCase(); const mode = $("#employer-footprint").value; const items = state.providers.filter(item => item.name.toLowerCase().includes(query) && (mode !== "multi" || item.states.length > 1) && (mode !== "repeat" || item.events > 1)); $("#employer-count").textContent = `${number.format(items.length)} provider${items.length === 1 ? "" : "s"}`; $("#employer-list").innerHTML = items.length ? items.map(item => `<tr><td><strong>${escapeHtml(item.name)}</strong><small>${escapeHtml(item.provider_types.join(" · ") || "Early-childhood services")}</small></td><td><span class="index-pill">${item.impact_index}</span></td><td>${number.format(item.events)}</td><td>${number.format(item.workers_affected)}</td><td>${escapeHtml(item.states.join(", ") || "—")}</td><td>${formatDate(item.latest_signal)}</td></tr>`).join("") : '<tr><td colspan="6">No providers match these filters.</td></tr>'; }
function renderTrendChart() { const metric = $("#trend-metric").value; const items = state.trends.slice(-18); const max = Math.max(...items.map(item => Number(item[metric] || 0)),1); $("#trend-chart").innerHTML = items.length ? items.map(item => `<div class="trend-column" title="${escapeHtml(item.month)}: ${number.format(item[metric])}"><span>${number.format(item[metric])}</span><i style="height:${Math.max(4,Math.round(item[metric] / max * 190))}px"></i><small>${escapeHtml(item.month.slice(2))}</small></div>`).join("") : '<div class="empty-card">No dated trends are available.</div>'; }
function renderProviderMix() { const counts = new Map(); state.notices.forEach(item => counts.set(item.provider_type,(counts.get(item.provider_type) || 0) + 1)); const items = [...counts.entries()].sort((a,b) => b[1]-a[1]); const max = Math.max(...items.map(item => item[1]),1); $("#provider-mix").innerHTML = items.map(([label,value]) => `<div class="bar-row"><div><strong>${escapeHtml(label)}</strong><span>${number.format(value)}</span></div><i><b style="width:${Math.round(value/max*100)}%"></b></i></div>`).join(""); }
function renderAlerts() { const workers = Number($("#alert-workers").value || 0); const score = Number($("#alert-score").value || 0); const items = state.notices.filter(item => Number(item.employees_affected || 0) >= workers && item.relevance_score >= score).slice(0,12); $("#alert-list").innerHTML = items.length ? items.map(item => `<button class="alert-item" data-open-id="${escapeHtml(item.id)}"><span class="alert-severity">${item.relevance_score >= 90 ? "Critical" : "Watch"}</span><strong>${escapeHtml(item.employer_name || "Unknown provider")}</strong><small>${number.format(item.employees_affected || 0)} workers · ${escapeHtml(item.state || "US")} · ${formatDate(item.effective_date || item.notice_date)}</small></button>`).join("") : '<div class="empty-card">No signals meet this alert threshold.</div>'; }
function renderValidationSources() { const query = $("#validation-search").value.trim().toLowerCase(); const type = $("#validation-type").value; const items = validationSources.filter(item => (type === "all" || item.type === type) && [item.name,item.organization,item.description,item.priority].join(" ").toLowerCase().includes(query)); $("#validation-count").textContent = `${items.length} source${items.length === 1 ? "" : "s"}`; $("#validation-list").innerHTML = items.map(item => `<article class="validation-card"><div><span class="source-type">${escapeHtml(item.priority)}</span><h3>${escapeHtml(item.name)}</h3><strong>${escapeHtml(item.organization)}</strong><p>${escapeHtml(item.description)}</p></div><a class="button secondary" href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">Open official site ↗</a></article>`).join(""); }
function updateValidationProgress() { const checked = $$("[data-validation-step]:checked"); const total = $$("[data-validation-step]").length; localStorage.setItem("lq-education-validation",JSON.stringify(checked.map(item => item.dataset.validationStep))); $("#validation-progress-bar").style.width = `${total ? checked.length / total * 100 : 0}%`; $("#validation-progress-label").textContent = `${checked.length} of ${total} complete`; }
function filteredLocations() { const query = $("#location-search").value.trim().toLowerCase(); const selectedState = $("#location-state").value; const brand = $("#location-brand").value; return state.locations.filter(item => (selectedState === "all" || item.state === selectedState) && (brand === "all" || item.brand === brand) && (!query || [item.name,item.brand,item.address,item.state].join(" ").toLowerCase().includes(query))); }
function renderLocations() { const items = filteredLocations(); $("#location-count").textContent = `${number.format(items.length)} location${items.length === 1 ? "" : "s"}`; $("#location-list").innerHTML = items.length ? items.map(item => `<article class="location-card" id="location-${escapeHtml(item.id)}"><span class="brand-chip ${item.brand === "Busy Bees" ? "busy" : "family"}">${escapeHtml(item.brand)}</span><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.address)}</p><a href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">View official center page ↗</a></article>`).join("") : '<div class="empty-card">No locations match these filters.</div>'; const visible = new Set(items.map(item => item.id)); $$(".location-pin",$("#locations-map")).forEach(pin => { pin.classList.toggle("hidden",!visible.has(pin.dataset.locationId)); }); }
function focusLocation(id) { const item = state.locations.find(location => location.id === id); if (!item) return; $$(".location-pin",$("#locations-map")).forEach(pin => pin.classList.toggle("selected",pin.dataset.locationId === id)); const card = $(`#location-${CSS.escape(id)}`); card?.scrollIntoView({ behavior:"smooth",block:"nearest" }); card?.classList.add("focused"); setTimeout(() => card?.classList.remove("focused"),1400); }
async function loadLocationsMap() { const markup = await fetch("assets/us-map.svg").then(response => response.text()); $("#locations-map").innerHTML = markup; const svg = $("svg",$("#locations-map")); if (!svg) return; state.locations.forEach(item => { if (item.longitude < -126 || item.longitude > -66 || item.latitude < 24 || item.latitude > 50) return; const circle = document.createElementNS("http://www.w3.org/2000/svg","circle"); circle.setAttribute("cx",String((item.longitude + 125) / 59 * 959)); circle.setAttribute("cy",String((50 - item.latitude) / 26 * 593)); circle.setAttribute("r","5"); circle.setAttribute("tabindex","0"); circle.setAttribute("aria-label",`${item.name}, ${item.address}`); circle.classList.add("location-pin",item.brand === "Busy Bees" ? "busy" : "family"); circle.dataset.locationId = item.id; const title = document.createElementNS("http://www.w3.org/2000/svg","title"); title.textContent = `${item.name} — ${item.address}`; circle.append(title); svg.append(circle); }); }
function openNotice(id) { const item = state.notices.find(notice => notice.id === id); if (!item) return; $("#dialog-content").innerHTML = `<div class="dialog-body"><p class="eyebrow">${escapeHtml(item.state || "US")} early-childhood signal</p><h2>${escapeHtml(item.employer_name || "Unknown provider")}</h2><p>${escapeHtml(item.site_name || item.organization_name || "Site details not reported")}</p><div class="detail-grid"><div class="detail"><span>Workers affected</span><strong>${item.employees_affected ? number.format(item.employees_affected) : "Not reported"}</strong></div><div class="detail"><span>Relevance score</span><strong>${item.relevance_score} · Directional</strong></div><div class="detail"><span>Notice date</span><strong>${formatDate(item.notice_date)}</strong></div><div class="detail"><span>Effective date</span><strong>${formatDate(item.effective_date)}</strong></div><div class="detail"><span>Location</span><strong>${escapeHtml([item.city,item.county,item.state].filter(Boolean).join(", ") || "Not reported")}</strong></div><div class="detail"><span>Provider type</span><strong>${escapeHtml(item.provider_type)}</strong></div></div><p>This match does not confirm that every affected worker is an educator or childcare worker.</p><div class="dialog-actions"><button class="button secondary" data-dialog-save="${escapeHtml(item.id)}">${state.saved.has(item.id) ? "Remove from saved" : "Save signal"}</button>${item.source_url ? `<a class="button" href="${escapeHtml(item.source_url)}" target="_blank" rel="noreferrer">Open source ↗</a>` : ""}</div></div>`; if (!$("#notice-dialog").open) $("#notice-dialog").showModal(); }
function csvCell(value) { return `"${String(value ?? "").replaceAll('"','""')}"`; }
function exportCsv(filename, rows, columns) { const csv = [columns.map(column => csvCell(column.label)).join(","), ...rows.map(row => columns.map(column => csvCell(row[column.key])).join(","))].join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([csv], { type:"text/csv;charset=utf-8" })); link.download = filename; link.click(); URL.revokeObjectURL(link.href); }
const noticeColumns = [["employer_name","Provider"],["site_name","Site"],["organization_name","Organization"],["city","City"],["county","County"],["state","State"],["employees_affected","Workers affected"],["notice_date","Notice date"],["effective_date","Effective date"],["relevance_score","Relevance score"],["provider_type","Provider type"],["source_name","Source"],["source_url","Source URL"]].map(([key,label]) => ({ key,label }));
const marketColumns = [["state","State"],["activity_index","Activity index"],["events","Signals"],["workers_affected","Workers affected"],["providers","Providers"],["latest_signal","Latest signal"]].map(([key,label]) => ({ key,label }));
const providerColumns = [["name","Provider"],["impact_index","Impact index"],["events","Signals"],["workers_affected","Workers affected"],["states","States"],["provider_types","Provider types"],["latest_signal","Latest signal"]].map(([key,label]) => ({ key,label }));
const locationColumns = [["name","Location"],["brand","Portfolio brand"],["address","Address"],["state","State"],["latitude","Latitude"],["longitude","Longitude"],["url","Official URL"]].map(([key,label]) => ({ key,label }));
const jobColumns = [["priority_rank","Priority rank"],["priority_score","Estimated priority score"],["priority_tier","Priority tier"],["first_observed_at","First observed by LightkeeperIQ"],["observed_open_days","Observed open days"],["priority_factors","Priority factors"],["id","Job ID"],["title","Job title"],["location","Center or market"],["state","State"],["department","Department"],["role_family","Role family"],["url","Official application URL"]].map(([key,label]) => ({ key,label }));
async function loadMap() { const markup = await fetch("assets/us-map.svg").then(response => response.text()); $("#us-map").innerHTML = markup; const counts = Object.fromEntries(state.metadata.stateCounts || []); const max = Math.max(...Object.values(counts),1); $$("path",$("#us-map")).forEach(path => { const code = path.getAttribute("class")?.split(" ")[0]?.toUpperCase(); if (!code || code.length !== 2) return; const ratio = Math.log1p(counts[code] || 0) / Math.log1p(max); path.style.fill = ratio > .72 ? "#2b6cb0" : ratio > .45 ? "#4299e1" : ratio > .2 ? "#90cdf4" : "#dbeafe"; path.dataset.state = code; path.tabIndex = 0; path.setAttribute("aria-label",`${friendlyState(code)}: ${counts[code] || 0} signals`); }); }
function setStateFilter(code) { $("#notice-state").value = code; state.page = 1; renderNotices(); $$("path",$("#us-map")).forEach(path => path.classList.toggle("selected",path.dataset.state === code)); const count = (state.metadata.stateCounts || []).find(([item]) => item === code)?.[1] || 0; $("#state-focus").innerHTML = code ? `<span class="state-code">${escapeHtml(code)}</span><h3>${escapeHtml(friendlyState(code))}</h3><p>${number.format(count)} matched signal${count === 1 ? "" : "s"}.</p><button class="text-button" id="clear-state">Clear state filter</button>` : '<span class="state-code">US</span><h3>National view</h3><p>Select a state to focus the signal feed.</p>'; }
function bindEvents() {
  $$("[data-route]").forEach(element => element.addEventListener("click", event => { event.preventDefault(); routeTo(element.dataset.route); }));
  ["notice-search","notice-state","notice-window","notice-score"].forEach(id => $(`#${id}`).addEventListener(id === "notice-search" ? "input" : "change",() => { state.page = 1; renderNotices(); }));
  $("#market-search").addEventListener("input",renderMarkets); ["compare-a","compare-b"].forEach(id => $(`#${id}`).addEventListener("change",renderComparison)); $("#swap-markets").addEventListener("click",() => { const value = $("#compare-a").value; $("#compare-a").value = $("#compare-b").value; $("#compare-b").value = value; renderComparison(); }); ["employer-search","employer-footprint"].forEach(id => $(`#${id}`).addEventListener(id === "employer-search" ? "input" : "change",renderEmployers)); $("#trend-metric").addEventListener("change",renderTrendChart); ["alert-workers","alert-score"].forEach(id => $(`#${id}`).addEventListener(id === "alert-workers" ? "input" : "change",renderAlerts)); $("#reset-notices").addEventListener("click",() => { $("#notice-search").value = ""; $("#notice-state").value = ""; $("#notice-window").value = "all"; $("#notice-score").value = "0"; setStateFilter(""); });
  ["validation-search","validation-type"].forEach(id => $(`#${id}`).addEventListener(id === "validation-search" ? "input" : "change",renderValidationSources)); $$("[data-validation-step]").forEach(input => input.addEventListener("change",updateValidationProgress)); $("#validation-reset").addEventListener("click",() => { $$("[data-validation-step]").forEach(input => { input.checked = false; }); updateValidationProgress(); });
  ["location-search","location-state","location-brand"].forEach(id => $(`#${id}`).addEventListener(id === "location-search" ? "input" : "change",renderLocations)); $("#location-reset").addEventListener("click",() => { $("#location-search").value = ""; $("#location-state").value = "all"; $("#location-brand").value = "all"; renderLocations(); }); $("#locations-map").addEventListener("click",event => { const pin = event.target.closest(".location-pin"); if (pin) focusLocation(pin.dataset.locationId); }); $("#locations-map").addEventListener("keydown",event => { const pin = event.target.closest(".location-pin"); if (pin && (event.key === "Enter" || event.key === " ")) focusLocation(pin.dataset.locationId); });
  $("#prev-page").addEventListener("click",() => { state.page--; renderNotices(); }); $("#next-page").addEventListener("click",() => { state.page++; renderNotices(); });
  document.addEventListener("click",event => { const save = event.target.closest("[data-save-id]"); const dialogSave = event.target.closest("[data-dialog-save]"); const market = event.target.closest("[data-market-state]"); const open = event.target.closest("[data-open-id], [data-notice-id]"); if (save) { event.stopPropagation(); saveNotice(save.dataset.saveId); } else if (dialogSave) { saveNotice(dialogSave.dataset.dialogSave); openNotice(dialogSave.dataset.dialogSave); } else if (market) { event.preventDefault(); setStateFilter(market.dataset.marketState); routeTo("radar"); } else if (open) openNotice(open.dataset.openId || open.dataset.noticeId); if (event.target.closest("#clear-state")) setStateFilter(""); });
  $("#us-map").addEventListener("click",event => { const path = event.target.closest("path[data-state]"); if (path) setStateFilter(path.dataset.state); }); $("#dialog-close").addEventListener("click",() => $("#notice-dialog").close()); $("#notice-dialog").addEventListener("click",event => { if (event.target === $("#notice-dialog")) $("#notice-dialog").close(); });
  $("#export-notices").addEventListener("click",() => exportCsv("lightkeeperiq-education-signals.csv",filteredNotices(),noticeColumns)); $("#export-saved").addEventListener("click",() => exportCsv("lightkeeperiq-education-saved.csv",state.notices.filter(item => state.saved.has(item.id)),noticeColumns)); $("#export-markets").addEventListener("click",() => exportCsv("lightkeeperiq-education-markets.csv",state.markets,marketColumns)); $("#export-employers").addEventListener("click",() => exportCsv("lightkeeperiq-education-employers.csv",state.providers,providerColumns));
  $("#export-locations").addEventListener("click",() => exportCsv("busy-bees-us-locations.csv",filteredLocations(),locationColumns));
  ["jobs-search","jobs-state","jobs-role","jobs-sort"].forEach(id => $(`#${id}`).addEventListener(id === "jobs-search" ? "input" : "change",renderJobs));
  $("#jobs-reset").addEventListener("click",() => { $("#jobs-search").value = ""; $("#jobs-state").value = "all"; $("#jobs-role").value = "all"; $("#jobs-sort").value = "priority"; renderJobs(); });
  $("#export-jobs").addEventListener("click",() => exportCsv("brightpath-active-jobs.csv",filteredJobs(),jobColumns));
  $("#logout-button").addEventListener("click",async () => { await fetch("/api/logout",{ method:"POST" }); location.replace("/login.html"); });
}
async function init() {
  bindEvents();
  try {
    const savedSteps = new Set(JSON.parse(localStorage.getItem("lq-education-validation") || "[]"));
    $$("[data-validation-step]").forEach(input => { input.checked = savedSteps.has(input.dataset.validationStep); });
    updateValidationProgress();
    renderValidationSources();
    const [data, locationData, jobData, jobHistoryData] = await Promise.all([
      fetch("data/education-intel.json").then(response => { if (!response.ok) throw new Error("Education data unavailable"); return response.json(); }),
      fetch("data/busy-bees-us-locations.json").then(response => { if (!response.ok) throw new Error("Location data unavailable"); return response.json(); }),
      fetch("data/brightpath-jobs.json").then(response => { if (!response.ok) throw new Error("BrightPath jobs unavailable"); return response.json(); }),
      fetch("data/brightpath-jobs-history.json").then(response => { if (!response.ok) throw new Error("BrightPath job history unavailable"); return response.json(); })
    ]);
    state.notices = data.notices || [];
    state.markets = data.markets || [];
    state.providers = data.providers || [];
    state.trends = data.trends || [];
    state.locations = locationData.locations || [];
    state.jobs = jobData.jobs || [];
    state.jobHistory = jobHistoryData.snapshots || [];
    state.jobMeta = jobData;
    state.newJobIds = new Set((jobData.newJobs || []).map(String));
    state.metadata = data.metadata || {};
    populateSelect($("#notice-state"),[...new Set(state.notices.map(item => item.state))]);
    populateSelect($("#location-state"),[...new Set(state.locations.map(item => item.state))]);
    populateSelect($("#jobs-state"),[...new Set(state.jobs.map(item => item.state))]);
    [...new Set(state.locations.map(item => item.brand))].sort().forEach(brand => { const option = document.createElement("option"); option.value = brand; option.textContent = brand; $("#location-brand").append(option); });
    state.markets.forEach(item => [$("#compare-a"),$("#compare-b")].forEach(select => { const option = document.createElement("option"); option.value = item.state; option.textContent = friendlyState(item.state); select.append(option); }));
    if (state.markets[1]) $("#compare-b").value = state.markets[1].state;
    $("#stat-notices").textContent = number.format(state.notices.length);
    $("#stat-workers").textContent = number.format(state.notices.reduce((sum,item) => sum + Number(item.employees_affected || 0),0));
    $("#stat-states").textContent = number.format(state.markets.length);
    $("#stat-strong").textContent = number.format(state.notices.filter(item => item.relevance_score >= 80).length);
    $("#stat-markets").textContent = number.format(state.markets.length);
    $("#stat-providers").textContent = number.format(state.providers.length);
    $("#stat-top-market").textContent = state.markets[0]?.state || "—";
    const latest = state.markets.map(item => item.latest_signal).filter(Boolean).sort().at(-1);
    $("#stat-latest").textContent = latest ? formatDate(latest) : "—";
    $("#employer-total").textContent = number.format(state.providers.length);
    $("#employer-multi").textContent = number.format(state.providers.filter(item => item.states.length > 1).length);
    $("#employer-repeat").textContent = number.format(state.providers.filter(item => item.events > 1).length);
    $("#employer-largest").textContent = number.format(Math.max(...state.providers.map(item => item.workers_affected),0));
    $("#location-total").textContent = number.format(state.locations.length);
    $("#location-states").textContent = number.format(new Set(state.locations.map(item => item.state)).size);
    $("#location-mapped").textContent = number.format(locationData.metadata?.mappedCount ?? state.locations.length);
    const locationStateCounts = state.locations.reduce((map,item) => map.set(item.state,(map.get(item.state) || 0) + 1),new Map());
    $("#location-top-state").textContent = [...locationStateCounts].sort((a,b) => b[1]-a[1])[0]?.[0] || "—";
    $("#saved-count").textContent = state.saved.size;
    const refreshed = state.metadata.lastUpdated ? formatDate(state.metadata.lastUpdated.slice(0,10)) : "date unavailable";
    $("#freshness-label").textContent = `Updated ${refreshed}`;
    $("#about-refresh").textContent = `This build contains ${number.format(state.notices.length)} matched signals across ${number.format(state.markets.length)} state markets, ${number.format(state.providers.length)} providers, and ${number.format(state.locations.length)} published Busy Bees family locations. Source data was last refreshed ${refreshed}.`;
    $("#jobs-total").textContent = number.format(state.jobs.length);
    $("#jobs-education").textContent = number.format(state.jobs.filter(item => item.role_family === "Education").length);
    $("#jobs-leadership").textContent = number.format(state.jobs.filter(item => item.role_family === "Leadership").length);
    $("#jobs-top-market").textContent = jobData.summary?.byState?.[0]?.[0] || "—";
    $("#jobs-captured").textContent = jobData.metadata?.capturedAt ? new Date(jobData.metadata.capturedAt).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"}) : "—";
    renderNotices(); renderMarkets(); renderComparison(); renderEmployers(); renderTrendChart(); renderProviderMix(); renderAlerts(); renderLocations(); renderJobs(); renderJobInsights(); renderSaved();
    await Promise.all([loadMap(),loadLocationsMap()]);
    routeTo(location.hash.slice(1) || "radar");
  } catch (error) {
    console.error(error);
    $$(".loading-card").forEach(card => card.textContent = "Education data could not be loaded. Run the data build and serve the app over HTTP.");
    $("#freshness-label").textContent = "Data unavailable";
  }
}
function filteredJobs() { const query = $("#jobs-search").value.trim().toLowerCase(); const selectedState = $("#jobs-state").value; const role = $("#jobs-role").value; const sort = $("#jobs-sort").value; const items=state.jobs.filter(item => (selectedState === "all" || item.state === selectedState) && (role === "all" || item.role_family === role) && (!query || [item.title,item.location,item.state,item.department,item.role_family,item.priority_tier,item.priority_factors].join(" ").toLowerCase().includes(query))); return items.sort((a,b) => sort === "title" ? a.title.localeCompare(b.title) : sort === "location" ? a.location.localeCompare(b.location) || a.title.localeCompare(b.title) : b.priority_score-a.priority_score || a.priority_rank-b.priority_rank); }
function renderJobs() { const items = filteredJobs(); $("#jobs-count").textContent = `${number.format(items.length)} ranked req${items.length === 1 ? "" : "s"}`; $("#jobs-list").innerHTML = items.length ? items.map(item => `<article class="job-card"><div class="priority-rank"><strong>#${number.format(item.priority_rank)}</strong><span>${item.priority_score}/100</span></div><div class="job-card-body"><span class="job-badge priority-${escapeHtml(item.priority_tier.toLowerCase())}">${escapeHtml(item.priority_tier)} priority</span><span class="job-badge">${escapeHtml(item.role_family)}</span>${state.newJobIds.has(String(item.id)) ? '<span class="job-badge new">New</span>' : ""}<h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.location)}${item.state ? `, ${escapeHtml(item.state)}` : ""} · ${escapeHtml(item.department || "Department not listed")}</p><p class="job-age">Observed open ${number.format(item.observed_open_days || 0)} day${item.observed_open_days === 1 ? "" : "s"} · Since ${formatDate(String(item.first_observed_at || "").slice(0,10))}</p><small>${escapeHtml((item.priority_factors || []).join(" · "))}</small></div><a class="button secondary" href="${escapeHtml(item.url)}" target="_blank" rel="noreferrer">View &amp; apply ↗</a></article>`).join("") : '<div class="empty-card">No active jobs match these filters.</div>'; }
function barsMarkup(items,limit = 10) { const visible = items.slice(0,limit); const max = Math.max(...visible.map(item => Number(item[1] || 0)),1); return visible.map(([label,value]) => `<div class="bar-row"><div><strong>${escapeHtml(label.length === 2 ? friendlyState(label) : label)}</strong><span>${number.format(value)}</span></div><i><b style="width:${Math.round(value/max*100)}%"></b></i></div>`).join(""); }
function renderJobInsights() { const byState = state.jobMeta.summary?.byState || []; const byRole = state.jobMeta.summary?.byRole || []; $("#jobs-state-bars").innerHTML = barsMarkup(byState); $("#jobs-role-bars").innerHTML = barsMarkup(byRole,byRole.length); const snapshots = state.jobHistory.slice(-30); const max = Math.max(...snapshots.map(item => item.total),1); $("#jobs-trend").innerHTML = snapshots.length ? snapshots.map(item => `<div class="job-trend-column" title="${escapeHtml(new Date(item.capturedAt).toLocaleString())}: ${number.format(item.total)} active"><span>${number.format(item.total)}</span><i style="height:${Math.max(8,Math.round(item.total/max*116))}px"></i><small>${escapeHtml(new Date(item.capturedAt).toLocaleDateString("en-US",{month:"short",day:"numeric"}))}</small></div>`).join("") : '<div class="empty-card">Trend history starts with the first snapshot.</div>'; const added = Number(state.jobMeta.metadata?.newCount || 0); const closed = Number(state.jobMeta.metadata?.closedCount || 0); $("#jobs-change-note").textContent = snapshots.length < 2 ? "Baseline captured. Future refreshes will show openings added and removed." : `${number.format(added)} added and ${number.format(closed)} removed since the prior snapshot.`; }
init();
